config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/toys", to: "toys#index", as: "toys"
  get "/toys/new", to: "toys#new", as: "new_toy"
  post "/toys", to: "toys#create"
  get "/toys/:id", to: "toys#show", as: "toy"
  get "/toys/:id/edit", to: "toys#edit", as: "edit_toy"
  put "/toys/:id", to: "toys#update"
  patch "/toys/:id", to: "toys#update"
  delete "/toys/:id", to: "toys#destroy"  

  get "/users", to: "users#index", as: "users"
  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  put "/users/:id", to: "users#update"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy"  

  get "/manufacturers", to: "manufacturers#index", as: "manufacturers"
  get "/manufacturers/new", to: "manufacturers#new", as: "new_manufacturer"
  post "/manufacturers", to: "manufacturers#create"
  get "/manufacturers/:id", to: "manufacturers#show", as: "manufacturer"
  get "/manufacturers/:id/edit", to: "manufacturers#edit", as: "edit_manufacturer"
  put "/manufacturers/:id", to: "manufacturers#update"
  patch "/manufacturers/:id", to: "manufacturers#update"
  delete "/manufacturers/:id", to: "manufacturers#destroy"  



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    has_many :toys, dependent: :destroy
end

app/models/toy.rb
class Toy < ApplicationRecord
    belongs_to :user
    belongs_to :manufacturer
end

app/models/user.rb
class User < ApplicationRecord
    has_many :toys, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController

    def index
        @manufacturers = Manufacturer.all.order(id: :asc)
    end

    def new
        @manufacturer = Manufacturer.new
    end

    def create
        whitelisted_params = params.require(:manufacturer).permit(:name, :location)
        manufacturer = Manufacturer.create(whitelisted_params)
        redirect_to manufacturer_path(manufacturer.id)
    end

    def show
        id = params[:id].to_i
        @manufacturer = Manufacturer.find(id)
    end

    def edit
        id = params[:id].to_i
        @manufacturer = Manufacturer.find(id)
    end

    def update

        id = params[:id].to_i
        manufacturer = Manufacturer.find(id)
        whitelisted_params = params.require(:manufacturer).permit(:name, :location)
        manufacturer.update(whitelisted_params)
        redirect_to manufacturer_path(id)

    end

    def destroy
        id = params[:id].to_i
        Manufacturer.find(id).destroy
        redirect_to manufacturers_path
    end

end

app/controllers/toys_controller.rb
class ToysController < ApplicationController

    def index
        @toys = Toy.all.order(posted: :asc)
    end

    def new
        @toy = Toy.new
    end

    def create
        whitelisted_params = params.require(:toy).permit(:name, :description, :posted, :user)
        toy = Toy.create(whitelisted_params)
        redirect_to toy_path(toy.id)
    end

    def show
        id = params[:id].to_i
        @toy = Toy.find(id)
    end

    def edit
        id = params[:id].to_i
        @toy = Toy.find(id)
        @options = User.pluck(:email).zip(User.pluck(:id))
    end

    def update

        id = params[:id].to_i
        toy = Toy.find(id)
        whitelisted_params = params.require(:toy).permit(:name, :description, :posted, :user_id)
        toy.update(whitelisted_params)
        redirect_to toy_path(id)

    end

    def destroy
        id = params[:id].to_i
        Toy.find(id).destroy
        redirect_to toys_path
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all.order(id: :asc)
    end

    def new
        @user = User.new
    end

    def create
        whitelisted_params = params.require(:user).permit(:email, :password)
        user = User.create(whitelisted_params)
        redirect_to user_path(user.id)
    end

    def show
        id = params[:id].to_i
        @user = User.find(id)
    end

    def edit
        id = params[:id].to_i
        @user = User.find(id)
    end

    def update

        id = params[:id].to_i
        user = User.find(id)
        whitelisted_params = params.require(:user).permit(:email, :password)
        user.update(whitelisted_params)
        redirect_to user_path(id)

    end

    def destroy
        id = params[:id].to_i
        User.find(id).destroy
        redirect_to users_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="center">
      <%= link_to "Toys", toys_path, class: "standard-button" %>
      <%= link_to "Users", users_path, class: "standard-button" %>
      <%= link_to "Manufacturers", manufacturers_path, class: "standard-button" %>
      
    </div>

    <%= yield %>
  </body>
</html>

app/views/manufacturers/edit.html.erb
<div id="edit">

    <h1>Edit Manufacturer</h1>

    <%= form_with model: @manufacturer, local: true do |form| %>

        <div>
            <%= form.label :name %>
            <%= form.text_field :name %>
        </div>

        <div>
            <%= form.label :location %>
            <%= form.text_field :location %>
        </div>

        <div>
            <%= form.submit :Update %>
        </div>

        <%= link_to("Back", manufacturers_path, class: "standard-button") %>

    <% end %>

</div>

app/views/manufacturers/index.html.erb
<div id="index">

    <h1>List of manufacturers</h1>
    <%= link_to("New Manufacturer", new_manufacturer_path, class: "standard-button") %>

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Location</th>
                <th class="link-column"></th>
                <th class="link-column"></th>
                <th class="link-column"></th>
            </tr>
        </thead>
        <tbody>

            <% @manufacturers.each do |manufacturer| %>
                <tr>
                    <td class="center"><%= manufacturer["id"] %></td>
                    <td><%= manufacturer["name"] %></td>
                    <td class="center"><%= manufacturer["location"] %></td>
                    <td><%= link_to("Show", manufacturer_path(manufacturer["id"])) %></td>
                    <td><%= link_to("Edit", edit_manufacturer_path(manufacturer["id"])) %></td>
                    <td><%= link_to("Delete", manufacturer_path(manufacturer["id"]), method: :delete, data: { confirm: 'Are you sure?' }) %></td>
                </tr>
            <% end %>

        </tbody>

    </table>

</div>

app/views/manufacturers/new.html.erb
<div id="new">

    <h1>New Manufacturer</h1>

    <%= form_with model: @manufacturer, local: true do |form| %>

        <div>
            <%= form.label :name %>
            <%= form.text_field :name %>
        </div>

        <div>
            <%= form.label :location %>
            <%= form.text_field :location %>
        </div>

        <div>
            <%= form.submit :Create %>
        </div>
        
        <%= link_to("Back", manufacturers_path, class: "standard-button") %>

    <% end %>

</div>

app/views/manufacturers/show.html.erb
<div id="show">

    <h1>Show Manufacturer Details</h1>

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Location</th>
                <th class="link-column"></th>
                <th class="link-column"></th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td><%= @manufacturer["id"] %></td>
                <td><%= @manufacturer["name"] %></td>
                <td><%= @manufacturer["location"] %></td>
                <td><%= link_to("Edit", edit_manufacturer_path(@manufacturer["id"])) %></td>
                <td><%= link_to("Delete", manufacturer_path(@manufacturer["id"])) %></td>
            </tr>

        </tbody>

    </table>

    <%= link_to("Back", manufacturers_path, class: "standard-button") %>

</div>

app/views/toys/edit.html.erb
<div id="edit">

    <h1>Edit Toy</h1>

    <%= form_with model: @toy, local: true do |form| %>

        <div>
            <%= form.label :name %>
            <%= form.text_field :name %>
        </div>

        <div>
            <%= form.label :description %>
            <%= form.text_area :description %>
        </div>

        <div>
            <%= form.label :posted %>
            <%= form.date_field :posted %>
        </div>

        <div>
            <%= form.label :user_id %>
            <%= form.select(:user_id, options_for_select(@options, @toy.user_id))%>
        </div>

        <div>
            <%= form.submit :Update %>
        </div>

        <%= link_to("Back", toys_path, class: "standard-button") %>

    <% end %>

</div>

app/views/toys/index.html.erb
<div id="index">

    <h1>List of Toys</h1>
    <%= link_to("New Toy", new_toy_path, class: "standard-button") %>

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Posted</th>
                <th>User</th>
                <th>Manufacturer_ID</th>
                <th class="link-column"></th>
                <th class="link-column"></th>
                <th class="link-column"></th>
            </tr>
        </thead>
        <tbody>

            <% @toys.each do |toy| %>
                <tr>
                    <td class="center"><%= toy["id"] %></td>
                    <td><%= toy["name"] %></td>
                    <td class="center"><%= toy["posted"] %></td>
                    <td><%= toy.user.email %></td>
                    <td><%= toy.manufacturer.name %></td>
                    <td><%= link_to("Show", toy_path(toy["id"])) %></td>
                    <td><%= link_to("Edit", edit_toy_path(toy["id"])) %></td>
                    <td><%= link_to("Delete", toy_path(toy["id"]), method: :delete, data: { confirm: 'Are you sure?' }) %></td>
                </tr>
            <% end %>

        </tbody>

    </table>

</div>

app/views/toys/new.html.erb
<div id="new">

    <h1>New Toy</h1>

    <%= form_with model: @toy, local: true do |form| %>

        <div>
            <%= form.label :name %>
            <%= form.text_field :name %>
        </div>

        <div>
            <%= form.label :description %>
            <%= form.text_area :description %>
        </div>

        <div>
            <%= form.label :posted %>
            <%= form.date_field :posted %>
        </div>

        <div>
            <%= form.label :user %>
            <%= form.text_field :user %>
        </div>

        <div>
            <%= form.submit :Create %>
        </div>
        
        <%= link_to("Back", toys_path, class: "standard-button") %>

    <% end %>

</div>

app/views/toys/show.html.erb
<div id="show">

    <h1>Show Toy Details</h1>

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Posted</th>
                <th>User</th>
                <th class="link-column"></th>
                <th class="link-column"></th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td><%= @toy["id"] %></td>
                <td><%= @toy["name"] %></td>
                <td><%= @toy["posted"] %></td>
                <td><%= @toy["user"] %></td>
                <td><%= link_to("Edit", edit_toy_path(@toy["id"])) %></td>
                <td><%= link_to("Delete", toy_path(@toy["id"])) %></td>
            </tr>

        </tbody>

    </table>

    <p>
        <%= @toy["description"] %>
    </p>

    <%= link_to("Back", toys_path, class: "standard-button") %>

</div>

app/views/users/edit.html.erb
<div id="edit">

    <h1>Edit User</h1>

    <%= form_with model: @user, local: true do |form| %>

        <div>
            <%= form.label :email %>
            <%= form.text_field :email %>
        </div>

        <div>
            <%= form.label :password %>
            <%= form.text_field :password %>
        </div>

        <div>
            <%= form.submit :Update %>
        </div>

        <%= link_to("Back", users_path, class: "standard-button") %>

    <% end %>

</div>

app/views/users/index.html.erb
<div id="index">

    <h1>List of Users</h1>
    <%= link_to("New User", new_user_path, class: "standard-button") %>

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Password</th>
                <th class="link-column"></th>
                <th class="link-column"></th>
                <th class="link-column"></th>
            </tr>
        </thead>
        <tbody>

            <% @users.each do |user| %>
                <tr>
                    <td class="center"><%= user["id"] %></td>
                    <td><%= user["email"] %></td>
                    <td class="center"><%= user["password"] %></td>
                    <td><%= link_to("Show", user_path(user["id"])) %></td>
                    <td><%= link_to("Edit", edit_user_path(user["id"])) %></td>
                    <td><%= link_to("Delete", user_path(user["id"]), method: :delete, data: { confirm: 'Are you sure?' }) %></td>
                </tr>
            <% end %>

        </tbody>

    </table>

</div>

app/views/users/new.html.erb
<div id="new">

    <h1>New User</h1>

    <%= form_with model: @user, local: true do |form| %>

        <div>
            <%= form.label :email %>
            <%= form.text_field :email %>
        </div>

        <div>
            <%= form.label :password %>
            <%= form.text_field :password %>
        </div>

        <div>
            <%= form.submit :Create %>
        </div>
        
        <%= link_to("Back", users_path, class: "standard-button") %>

    <% end %>

</div>

app/views/users/show.html.erb
<div id="show">

    <h1>Show User Details</h1>

    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Password</th>
                <th class="link-column"></th>
                <th class="link-column"></th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td><%= @user["id"] %></td>
                <td><%= @user["email"] %></td>
                <td><%= @user["password"] %></td>
                <td><%= link_to("Edit", edit_user_path(@user["id"])) %></td>
                <td><%= link_to("Delete", user_path(@user["id"])) %></td>
            </tr>

        </tbody>

    </table>

    <%= link_to("Back", users_path, class: "standard-button") %>

</div>